services:
  db:
    image: postgres:16
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    env_file:
      - ./.env

  web:
    build:
      context: .
      target: python-app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: db

  nginx:
    build:
      context: .
      target: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - web

  celery:
    build:
      context: .
      target: python-app
    command: >
      bash -c "python -m celery -A config worker --loglevel=info --pool=solo"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  celery-beat:
    build:
      context: .
      target: python-app
    command: >
      bash -c "python -m celery -A config beat -l info"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - celery

volumes:
  postgres_data:
  redis_data: