# Generated by Django 5.2.4 on 2025-07-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PleasantHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='место')),
                ('habit_time', models.TimeField(blank=True, null=True, verbose_name='время для выполнения привычки')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('frequency', models.IntegerField(verbose_name='периодичность')),
                ('time_to_complete', models.IntegerField(default=1, verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
            ],
            options={
                'verbose_name': 'Полезная привычка',
                'verbose_name_plural': 'Полезные привычки',
            },
        ),
        migrations.CreateModel(
            name='UsefulHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='место')),
                ('habit_time', models.TimeField(verbose_name='время для выполнения привычки')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('frequency', models.IntegerField(verbose_name='периодичность в днях')),
                ('time_to_complete', models.IntegerField(default=1, verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('award', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Приятная привычка',
                'verbose_name_plural': 'Приятные привычки',
            },
        ),
    ]
