# Generated by Django 5.2.4 on 2025-07-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pleasanthabit',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='usefulhabit',
            old_name='user',
            new_name='owner',
        ),
    ]
