# Generated by Django 5.2.4 on 2025-07-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_rename_user_pleasanthabit_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleasanthabit',
            name='frequency',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='pleasanthabit',
            name='time_to_complete',
            field=models.IntegerField(verbose_name='время на выполнение'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='frequency',
            field=models.IntegerField(default=1, verbose_name='периодичность в днях'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='time_to_complete',
            field=models.IntegerField(verbose_name='время на выполнение'),
        ),
    ]
