# Generated by Django 5.2.4 on 2025-07-24 16:43

import habit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_alter_pleasanthabit_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleasanthabit',
            name='frequency',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[habit.models.validate_less_than_7], verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='pleasanthabit',
            name='time_to_complete',
            field=models.IntegerField(verbose_name='время на выполнение в сек.'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='frequency',
            field=models.IntegerField(default=1, validators=[habit.models.validate_less_than_7], verbose_name='периодичность в днях'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='time_to_complete',
            field=models.IntegerField(verbose_name='время на выполнение в сек.'),
        ),
    ]
