name: Django CI

on: [push, pull_request]

env:
  DJANGO_SETTINGS_MODULE: config.settings
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        id: cache-venv
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-root
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Run PEP8 compliance check
        run: |
          poetry run flake8 .

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        id: cache-venv-test
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-root
        if: steps.cache-venv-test.outputs.cache-hit != 'true'
          
      - name: Run migrate
        run: python manage.py migrate

      - name: Run test
        run: python manage.py test
